Removed indentation errors
Signed-off-by: MdSahil-oss <Mohdssahil1@gmail.com>

diff --git a/test/conformance/kuttl/generate/policy/standard/data/sync/pol-foreach-data-sync-valid/01-script-try-create.yaml b/test/conformance/kuttl/generate/policy/standard/data/sync/pol-foreach-data-sync-valid/01-script-try-create.yaml
--- a/test/conformance/kuttl/generate/policy/standard/data/sync/pol-foreach-data-sync-valid/01-script-try-create.yaml
+++ b/test/conformance/kuttl/generate/policy/standard/data/sync/pol-foreach-data-sync-valid/01-script-try-create.yaml
@@ -2,12 +2,12 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
-- script: |
-    if kubectl apply -f policy.yaml
-    then
-      echo "Test succeeded. Policy was created as intended."
-      exit 0 
-    else 
-      echo "Tested failed. Policy was not created when it should have been."
-      exit 1
-    fi
+  - script: |
+      if kubectl apply -f policy.yaml
+      then
+        echo "Test succeeded. Policy was created as intended."
+        exit 0 
+      else 
+        echo "Tested failed. Policy was not created when it should have been."
+        exit 1
+      fi
