Revert "Merge branch 'kyverno:main' into mohamedasifs123-patch-2"
This reverts commit 1a357820f77696c7810d0394a67145353b88f467, reversing
changes made to 5b5dcbe4f45b664514a455886d8ff49f3e8253ad.

diff --git a/test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/operator-allnotin-01/chainsaw-test.yaml b/test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/operator-allnotin-01/chainsaw-test.yaml
--- a/test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/operator-allnotin-01/chainsaw-test.yaml
+++ b/test/conformance/chainsaw/validate/clusterpolicy/standard/enforce/operator-allnotin-01/chainsaw-test.yaml
@@ -14,10 +14,15 @@ spec:
   - name: step-02
     try:
     - script:
-        content: kubectl apply -f resource.yaml
-        check:
-          # This check below ensures that the string "label ''app.kubernetes.io/name'' is required" is found in stderr or else fails
-          (contains($stderr, 'label \'\'app.kubernetes.io/name\'\' is required')): true
+        content: |
+          if kubectl apply -f resource.yaml 2>&1 | grep -q "label ''app.kubernetes.io/name'' is required"
+          then
+            echo "Test succeeded. Resource was blocked from label."
+            exit 0
+          else
+            echo "Tested failed. Resource was allowed to create."
+            exit 1
+          fi
   - name: step-03
     try:
     - apply:
